#!/usr/bin/env bash

# ls
alias ls='eza'
alias l='ls -lha'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias t='tree'
alias t1='tree -L 1'
alias t2='tree -L 2'
alias t3='tree -L 3'

# safe file manipulation
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

# neovim
alias nv='nvim'
alias vim='nvim'
alias vi='nvim'
alias nvimc='rm -I $VIMCONFIG/swap/*'		# clean nvim swap file
alias nvimcu='rm -I $VIMCONFIG/undo/*'		# clean nvim undo
alias nviml='nvim -w $VIMCONFIG/vimlog "$@"'	# log the keystrokes
alias nvimd='nvim --noplugin -u NONE'		# launch nvim without any plugins or config (nvim debug)
alias nviml='nvim -c "set nowrap|syntax off"'	# fast nvim, for big files

# git
alias gs='git status'
alias gss='git status -s'
alias ga='git add'
alias gp='git push'
alias gpraise='git blame'
alias gpo='git push origin'
alias gplo='git pull origin'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout'
alias gl='git log --oneline'
alias gr='git remote'
alias grs='git remote show'
alias glol='git log --graph --abbrev-commit --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d" # Delete local branch merged with master
alias dif='git diff --no-index'

# tmux
alias tmuxk='tmux kill-session -t'
alias tumuxa='tmux attach -t'
alias tmuxl='tmux list-sessions'

# bat
alias batl='bat --paging=never -l log'

# functional
alias resource_zsh='source $ZDOTDIR/.zshrc'

# directory stack navigation
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

